"""init

Revision ID: 6d91f9a0c7dd
Revises: 
Create Date: 2025-03-23 23:46:28.981730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from utils import hash_string

# revision identifiers, used by Alembic.
revision: str = '6d91f9a0c7dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('fullname', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hash_password', sa.String(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('accounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('transaction_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('transaction_id')
                    )
    user_table = sa.table(
        'users',
        sa.column('fullname', sa.String()),
        sa.column('email', sa.String()),
        sa.column('hash_password', sa.String()),
        sa.column('is_admin', sa.Boolean()),
    )
    op.bulk_insert(user_table, [
        {
            'fullname': 'Test_User',
            'email': 'user1@example.com',
            'hash_password': hash_string('123456'),
            'is_admin': False
        },
        {
            'fullname': 'Test_Admin',
            'email': 'admin@example.com',
            'hash_password': hash_string('qwerty'),
            'is_admin': True
        }
    ])

    account = sa.table(
        'accounts',
        sa.column('user_id', sa.Integer()),
        sa.column('balance', sa.Float())
    )
    op.bulk_insert(account, [
        {
            'user_id': 1,
            'balance': 0.0
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
